### ISSUE TITLE
Deploy to Holesky testnet

### ISSUE THREAD

**Issue by wjmelements** [balancer/balancer-deployments#105]
Goerli is deprecated. Please deploy to holesky this year.

**Comment by wjmelements** [comment]
https://github.com/eth-clients/holesky

**Comment by wjmelements** [comment]
chain ID 17000
explorer https://holesky.etherscan.io

**Comment by gosuto-inzasheru** [comment]
goerli testnet was replaced by sepolia, for which there are deployments: https://github.com/balancer/balancer-deployments/blob/master/addresses/sepolia.json
