### ISSUE TITLE
# Description

### ISSUE THREAD

**Issue by jamiegreen7** [balancer/balancer-deployments#142]
# Description

This PR adds functions for deploying and verifying contracts using factories. 

## Type of change

- [x] Bug fix 
- [X] New feature 
- [ ] Breaking change 
- [ ] Dependency changes
- [ ] Code refactor / cleanup
- [x] Documentation or wording changes
- [ ] Other

## Checklist:

- [X] The diff is legible and has no extraneous changes
- [X] Complex code has been commented, including external interfaces
- [X] Tests are included for all code paths
- [X] The base branch is either `master`, or there's a description of how to merge

## Issue Resolution

_Originally posted by @elshan-eth in https://github.com/balancer/balancer-deployments/pull/132_

**Comment by jubeira** [comment]
?

blocked.
